### ISSUE TITLE
在RNS 项目下，找不到 com.jstarcraft.core.utility.Configurator

### ISSUE THREAD

**Issue by jifeer** [HongZhaoHua/jstarcraft-rns#3]
在RNS 项目下，找不到 com.jstarcraft.core.utility.Configurator，错误信息如图：
![image](https://user-images.githubusercontent.com/9289665/84456589-f2fb9c80-ac92-11ea-863c-1ec9341cd153.png)

**Comment by HongZhaoHua** [comment]
你应该是core,ai以及rns代码没有更新到最新.
Configurator已经不在com.jstarcraft.core.utility目录之下.

**Comment by HongZhaoHua** [comment]
你把core,ai和rns更新到最新,再重新install.

**Comment by jifeer** [comment]
你是对的，本地代码旧了
