### ISSUE TITLE
多态没有支持？

### ISSUE THREAD

**Issue by jifeer** [HongZhaoHua/jstarcraft-rns#4]
![image](https://user-images.githubusercontent.com/9289665/84457725-fb090b80-ac95-11ea-81eb-0a30dcb03515.png)

**Comment by jifeer** [comment]
感觉是core包代码不是最新的

**Comment by HongZhaoHua** [comment]
Int2FloatMap是非泛型的Map,比起Map<Integer,Float>,能够避免隐式转化,提高性能.
